server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        #Nacos的地址
        server-addr: 127.0.0.1:8848
  application:
    #服务名称
    name: api-passenger
  #默认可以配置，也可以不配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
