server:
  port: 8088

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: api-driver
